#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(HWSS_PHY_EVENT);
ESP_EVENT_DECLARE_BASE(HWSS_HIR_EVENT);
ESP_EVENT_DECLARE_BASE(HWSS_SIR_EVENT);
ESP_EVENT_DECLARE_BASE(HWSS_SSCM_EVENT);
ESP_EVENT_DECLARE_BASE(HWSS_HSL_EVENT);

typedef enum{
    HWSS_PHY_EVENT_CONNECT=0x01,
    HWSS_PHY_EVENT_DISCONN=0x02,
}hwss_phy_event;

typedef enum{
    HWSS_HIR_EVENT_TRIGGER=0x03
}hwss_hir_event;

typedef enum{
    HWSS_SIR_EVENT_IP_CONFLICT=0x04,
    HWSS_SIR_EVENT_DEST_UNREACH=0x05,
    HWSS_SIR_EVENT_PPPOE_CLOSE=0x06,
    HWSS_SIR_EVENT_MAGIC_PACK=0x07,
}hwss_sir_event;
    
typedef enum{
    HWSS_SSCM_EVENT_SEND_OK=0x08,
    HWSS_SSCM_EVENT_TIMEOUT=0x09,
    HWSS_SSCM_EVENT_RECV=0x0A,
    HWSS_SSCM_EVENT_DISCONN=0x0B,
    HWSS_SSCM_EVENT_CONNECT=0x0C,
}hwss_sscm_event;

typedef enum{
    HWSS_HSL_EVENT_TIMEOUT=0x0D,
    HWSS_HSL_EVENT_ARP=0x0E,
    HWSS_HSL_EVENT_PING=0x0F,
}hwss_hsl_event;

#define HWSS_SOCK_EVENTBIT_SEND_OK              1<<0
#define HWSS_SOCK_EVENTBIT_TIMEOUT              1<<1
#define HWSS_SOCK_EVENTBIT_RECV                 1<<2
#define HWSS_SOCK_EVENTBIT_DISCONN              1<<3
#define HWSS_SOCK_EVENTBIT_CONNECT              1<<4
#define HWSS_SOCK_EVENTBIT_CLOSE                1<<5


#define HWSS_PHY_EVENTBIT_CONNECTED             1<<0
#define HWSS_PHY_EVENTBIT_DISCONNECTED          1<<1

#define HWSS_HSL_EVENTBIT_TIMEOUT               1<<2
#define HWSS_HSL_EVENTBIT_ARP                   1<<3
#define HWSS_HSL_EVENTBIT_PING                  1<<4

#define HWSS_SIR_EVENTBIT_IP_CONFLICT           1<<10
#define HWSS_SIR_EVENTBIT_DEST_UNREACH          1<<11
#define HWSS_SIR_EVENTBIT_PPPOE_CLOSE           1<<12
#define HWSS_SIR_EVENTBIT_MAGIC_PACK            1<<13

#define HWSS_HIR_EVENTBIT_TRIGGER               1<<14
