#pragma once

#include "freertos/event_groups.h"
#include "esp_event.h"

typedef enum{
    HWSS_EVENT_CONNECTED,
    HWSS_EVENT_DISCONNECTED,
}hwss_event_t;

typedef enum{
    HWSS_INTER_EVENT_PHY_CONNECT=0x01,
    HWSS_INTER_EVENT_PHY_DISCONN=0x02,

    HWSS_INTER_EVENT_HIR_TRIGGER=0x03,

    HWSS_INTER_EVENT_HSO_SEND_OK=0x04,
    HWSS_INTER_EVENT_HSO_TIMEOUT=0x05,
    HWSS_INTER_EVENT_HSO_RECV=0x06,
    HWSS_INTER_EVENT_HSO_DISCONN=0x07,
    HWSS_INTER_EVENT_HSO_CONNECT=0x08,

    HWSS_INTER_EVENT_HSL_TIMEOUT=0x09,
    HWSS_INTER_EVENT_HSL_ARP=0x0A,
    HWSS_INTER_EVENT_HSL_PING=0x0B,

    HWSS_INTER_EVENT_HNET_IP_CONFLICT=0x0D,
    HWSS_INTER_EVENT_HNET_DEST_UNREACH=0x0F,
    HWSS_INTER_EVENT_HNET_PPPOE_CLOSE=0x10,
    HWSS_INTER_EVENT_HNET_MAGIC_PACK=0x11,
}hwss_inter_event_t;

#define HWSS_EVENT_ANY_ID                       -1
#define HWSS_EVENT_ANY_BASE                     NULL

ESP_EVENT_DECLARE_BASE(HWSS_EVENT);
ESP_EVENT_DECLARE_BASE(HWSS_INTER_EVENT);

#define HWSS_PHY_EVENTBIT_CONNECTED             1<<0
#define HWSS_PHY_EVENTBIT_DISCONNECTED          1<<1

#define HWSS_HSL_EVENTBIT_TIMEOUT               1<<2
#define HWSS_HSL_EVENTBIT_ARP                   1<<3
#define HWSS_HSL_EVENTBIT_PING                  1<<4

#define HWSS_HSO_EVENTBIT_SEND_OK               1<<5
#define HWSS_HSO_EVENTBIT_TIMEOUT               1<<6
#define HWSS_HSO_EVENTBIT_RECV                  1<<7
#define HWSS_HSO_EVENTBIT_DISCONN               1<<8
#define HWSS_HSO_EVENTBIT_CONNECT               1<<9

#define HWSS_HNET_EVENTBIT_IP_CONFLICT          1<<10
#define HWSS_HNET_EVENTBIT_DEST_UNREACH         1<<11
#define HWSS_HNET_EVENTBIT_PPPOE_CLOSE          1<<12
#define HWSS_HNET_EVENTBIT_MAGIC_PACK           1<<13

#define HWSS_HIR_EVENTBIT_TRIGGER               1<<14
