#include "hwss_eth_event.h"

ESP_EVENT_DEFINE_BASE(HWSS_PHY_EVENT);
ESP_EVENT_DEFINE_BASE(HWSS_HIR_EVENT);
ESP_EVENT_DEFINE_BASE(HWSS_SIR_EVENT);
ESP_EVENT_DEFINE_BASE(HWSS_SSCM_EVENT);
ESP_EVENT_DEFINE_BASE(HWSS_HSL_EVENT);
